In [5]:
import pandas as pd
import os
import glob
import numpy as np
import re

In [6]:
directory_path = "//"
csv_files = glob.glob(os.path.join(directory_path, "*.csv"))

print(f"Found {len(csv_files)} CSV files.")

Found 5 CSV files.

In [27]:
illuminate = pd.read_csv(
    os.path.join(directory_path, "Data/IlluminateData2025.csv"),
    encoding='cp1252',
    low_memory=True
)

In [8]:
final_df = pd.read_csv(
    os.path.join(directory_path, "Final_DF.csv"),
    low_memory=True
)

/var/folders/h6/zpsbdpxs6dxg5vq66fkdgnr00000gp/T/ipykernel_67410/3383152201.py:1: DtypeWarning: Columns (9,12,20) have mixed types. Specify dtype option on import or set low_memory=False.
  final_df = pd.read_csv(

In [28]:
illuminate.rename(columns={'Mask_StudentPersonkey': 'student_id'}, inplace=True)

In [13]:
for col in illuminate.columns:
    unique_vals = illuminate[col].unique()
    print(f"Column: {col} ({len(unique_vals)} unique values)")
    print(unique_vals[:10])  # Show first 10
    print("-" * 50)

Column: schoolyearnumberspring (1 unique values)
[2025]
--------------------------------------------------
Column: unitnumber (13 unique values)
['3' '2' '4' '1' '9' '8' '5' '6' '7' '5A']
--------------------------------------------------
Column: student_id (75082 unique values)
[406954 405935 728618 728056 728145 581810 612266 575620 397028 389057]
--------------------------------------------------
Column: title (5 unique values)
['language arts' 'math' 'Language Arts' 'social sciences' 'Science']
--------------------------------------------------
Column: AssessmentId (224 unique values)
[379494 356052 379314 357687 383115 341795 392299 356893 338215 376921]
--------------------------------------------------
Column: responsedatevalue (241 unique values)
['2025-01-13 00:00:00' '2024-10-14 00:00:00' '2025-02-14 00:00:00'
 '2024-12-19 00:00:00' '2025-02-11 00:00:00' '2024-09-16 00:00:00'
 '2025-03-26 00:00:00' '2024-09-20 00:00:00' '2024-12-17 00:00:00'
 '2024-11-11 00:00:00']
--------------------------------------------------
Column: DateValue (241 unique values)
['2025-01-13 00:00:00' '2024-10-14 00:00:00' '2025-02-14 00:00:00'
 '2024-12-19 00:00:00' '2025-02-11 00:00:00' '2024-09-16 00:00:00'
 '2025-03-26 00:00:00' '2024-09-20 00:00:00' '2024-12-17 00:00:00'
 '2024-11-11 00:00:00']
--------------------------------------------------
Column: Response_points (276 unique values)
[10.   12.   11.5  12.5   3.   21.34  9.   16.   14.   30.  ]
--------------------------------------------------
Column: Response_points_possible (30 unique values)
[14. 17. 15. 13. 10. 25. 11. 31. 29.  6.]
--------------------------------------------------
Column: Response_percent_correct (1113 unique values)
[71.43 70.59 76.67 96.15 30.   85.36 81.82 64.29 94.12 82.35]
--------------------------------------------------
Column: Department (5 unique values)
['language arts' 'math' 'Language Arts' 'social sciences' 'Science']
--------------------------------------------------
Column: rn (1 unique values)
[1]
--------------------------------------------------
Column: CurrentSchoolName (113 unique values)
['Northwestern Middle' 'Sandtown Middle' 'Riverwood High'
 'Hopewell Middle' 'Lake Windward Elementary' 'Wolf Creek Elementary'
 'Liberty Point Elementary' 'Sandy Springs Middle' 'Johns Creek High'
 'Paul D. West Middle School']
--------------------------------------------------
Column: standard_id (907 unique values)
[ 61826 192360  62529 192623  62267  61816 101120 193146 192271  61927]
--------------------------------------------------
Column: StandardStateNumber (898 unique values)
['ELAGSE6RL4' '6.NR.2.4' 'ELAGSE9-10L2a' '7.PAR.4.2' 'ELAGSE3L4'
 'ELAGSE3RL3' 'SS8H12.c' '3.GSR.7.2' '7.NR.1.10' 'ELAGSE9-10RI3']
--------------------------------------------------
Column: Standard_Subject (4 unique values)
['English Language Arts' 'Georgia’s K-12 Mathematics Standards'
 'Social Studies' 'Science']
--------------------------------------------------
Column: Standard_points (51 unique values)
[2.  1.  3.  6.  0.  7.  5.  4.  2.5 1.5]
--------------------------------------------------
Column: Standard_points_possible (14 unique values)
[ 2.  1.  3.  6.  8.  5.  4. 10.  7. 11.]
--------------------------------------------------
Column: Standard_percent_correct (132 unique values)
[100.    50.     0.    66.67  87.5   25.    80.    75.    83.33  67.  ]
--------------------------------------------------
Column: condition (3 unique values)
['Extension' 'Reteach' 'Review & Practice']
--------------------------------------------------
Column: pointsvarchar (109 unique values)
['2/2' '1/1' '3/3' '1/2' '6/6' '0/1' '2/3' '7/8' '0/2' '5/5']
--------------------------------------------------
Column: categorytitle (30 unique values)
['Grade 6' '6th Grade' 'Grades: 9-10' '7th Grade' 'Grade 3'
 'Eighth Grade – Georgia Studies' '3rd Grade' 'United States History'
 'Grade 8' 'Grade 7']
--------------------------------------------------
Column: stdgrouping (901 unique values)
['ELAGSE6RL4 Determine the meaning of words and phrases as they are used in a text, including figurative and connotative meanings; analyze the impact of a specific word choice on meaning and tone.'
 '6.NR.2.4 Design simple experiments and collect data. Use data gathered from realistic scenarios and simulations to determine quantitative measures of center (median and/or mean) and variability (interquartile range and range). Use these quantities to draw conclusions about the data, compare different numerical data sets, and make predictions.'
 'ELAGSE9-10L2a Use a semicolon (and perhaps a conjunctive adverb) to link two or more closely related independent clauses.'
 '7.PAR.4.2 Determine the unit rate (constant of proportionality) in tables, graphs (1, r), equations, diagrams, and verbal descriptions of proportional relationships to solve realistic problems.'
 'ELAGSE3L4 Determine or clarify the meaning of unknown and multiple-meaning words and phrases based on grade 3 reading and content, choosing flexibly from a range of strategies.'
 'ELAGSE3RL3 Describe characters in a story (e.g., their traits, motivations, or feelings) and explain how their actions contribute to the sequence of events.'
 'SS8H12.c Evaluate the short-term and long-term impacts of hosting the 1996 Olympics on Georgia’s economic and population growth.'
 '3.GSR.7.2 Determine the area of rectangles (or shapes composed of rectangles) presented in relevant problems by tiling and counting.'
 '7.NR.1.10 Convert rational numbers between forms to include fractions, decimal numbers and percentages, using understanding of the part divided by the whole. Know that the decimal form of a rational number terminates in 0s or eventually repeats.'
 'ELAGSE9-10RI3 Analyze how the author unfolds an analysis or series of ideas or events, including the order in which the points are made, how they are introduced and developed, and the connections that are drawn between them.']
--------------------------------------------------
Column: SchoolId (113 unique values)
[ 63 103  77 102  61 191 100  67 115 134]
--------------------------------------------------
Column: GradeLevelDuringUnitTest (15 unique values)
['06' '09' '03' '08' '07' '11' '05' 'KK' '04' '02']
--------------------------------------------------
Column: ContinuousAchievementLevel (7 unique values)
['On Level' 'Advanced' 'Not Applicable' nan 'Accelerated' 'Enhanced'
 'Unknown']
--------------------------------------------------
Column: AssessmentGradeLevel (13 unique values)
['6' '10' '7' '3' '8' '9' 'HS' '5' 'KinderGarten' '4']
--------------------------------------------------
Column: CurrentSchoolDetailFCSID (113 unique values)
[682 697 845 699 654 621 605 692 741 694]
--------------------------------------------------

In [11]:
for col in final_df.columns:
    unique_vals = final_df[col].unique()
    print(f"Column: {col} ({len(unique_vals)} unique values)")
    print(unique_vals[:10])  # Show first 10
    print("-" * 50)

Column: GradeLevel (4 unique values)
[ 9 10 11 12]
--------------------------------------------------
Column: SchoolYearId (3 unique values)
[33 34 35]
--------------------------------------------------
Column: SchoolYear (3 unique values)
['2022-2023' '2023-2024' '2024-2025']
--------------------------------------------------
Column: MarkingPeriodCode (7 unique values)
['S1' 'S2' 'R1' 'X6' 'X4' 'X2' 'Q2']
--------------------------------------------------
Column: MarkingPeriodStartDate (15 unique values)
['2022-08-08 00:00:00.000' '2023-01-04 00:00:00.000'
 '2023-05-31 00:00:00.000' '2023-04-17 00:00:00.000'
 '2022-09-22 00:00:00.000' '2023-08-07 00:00:00.000'
 '2024-01-03 00:00:00.000' '2023-10-09 00:00:00.000'
 '2024-06-05 00:00:00.000' '2024-04-15 00:00:00.000']
--------------------------------------------------
Column: MarkingPeriodEndDate (14 unique values)
['2022-12-16 00:00:00.000' '2023-05-25 00:00:00.000'
 '2023-07-12 00:00:00.000' '2023-02-17 00:00:00.000'
 '2022-11-02 00:00:00.000' '2023-12-15 00:00:00.000'
 '2024-05-23 00:00:00.000' '2024-07-10 00:00:00.000'
 '2024-02-16 00:00:00.000' '2023-11-01 00:00:00.000']
--------------------------------------------------
Column: SchoolDetailFCSId (50 unique values)
[852. 804. 741. 866. 751. 754. 743. 816. 740. 880.]
--------------------------------------------------
Column: SchoolStateId (50 unique values)
[ 191.  106.  910.  198.  203.  205.  119. 4062.  176.  392.]
--------------------------------------------------
Column: CourseLevelDesc (3 unique values)
['Level 2 Honors' 'Level 1 Non Honors' nan]
--------------------------------------------------
Column: CourseNumber (4994 unique values)
[23.0620041 40.0110042 23.0610051 26.2120041 26.0120042 23.0610041
 23.2610041 23.2620042 40.0510042 26.0120041]
--------------------------------------------------
Column: CourseDesc (1151 unique values)
['10th Grade Literature/Composition H' 'Physical Science H'
 '9th Grade Literature and Composition H M' 'Biology H'
 '9th Grade Literature and Composition H'
 '9th Grade Literature/Composition H' 'Chemistry H' 'Biology H M' nan
 '9th Grade Literature and Composition']
--------------------------------------------------
Column: DepartmentDesc (13 unique values)
['LANGUAGE ARTS' 'SCIENCE' 'FINE ARTS'
 'CAREER TECHNICAL AND AGRICULTURAL EDUCATION' 'PE/HEALTH'
 'WORLD LANGUAGES' 'SOCIAL SCIENCES' 'MATH' 'MISCELLANEOUS'
 'HEALTH EDUCATION']
--------------------------------------------------
Column: DOECourseNumber (1289 unique values)
[23.062 40.011 23.061 26.012 40.051 52.061 52.062 26.0611 6.415 8.474]
--------------------------------------------------
Column: StartPeriodCode (33 unique values)
['1' '6' '2' '3' '7' '5' '4' '8' 'FVS' nan]
--------------------------------------------------
Column: EndPeriodCode (27 unique values)
['1' '6' '2' '3' '7' '5' '4' '8' 'FVS' nan]
--------------------------------------------------
Column: SchoolCourseDesc (2230 unique values)
['10th Lit/Comp H' 'Phys Sci H' '9th Lit/Comp H M' 'Biology H'
 '9th Lit/Comp H' 'Chemistry H' 'Biology H M' 'Acting I M' 'Acting II M'
 '9th Lit/Comp']
--------------------------------------------------
Column: AttemptedCredit (5 unique values)
[0.5  1.   0.   1.5  0.55]
--------------------------------------------------
Column: EarnedCredit (3 unique values)
[0.5 1.  1.5]
--------------------------------------------------
Column: MarkTypeCode (2 unique values)
['S18' nan]
--------------------------------------------------
Column: MarkTypeDesc (2 unique values)
['Semester' nan]
--------------------------------------------------
Column: Mark (85 unique values)
[100 99 97 98 101 102 92 93 91 104]
--------------------------------------------------
Column: StaffPersonKey (2523 unique values)
[  7186. 110809.   3931. 111252.  65417. 110917.  26439.  68495.  15494.
  22022.]
--------------------------------------------------
Column: student_id (48622 unique values)
[370673 311666 329248 354631 331279 363414 356524 331242 331736 331645]
--------------------------------------------------
Column: SchoolLevel (1 unique values)
['High']
--------------------------------------------------
Column: CredStill_ELA (12 unique values)
[2.  1.5 1.  0.  nan 2.5 0.5 3.  4.  3.5]
--------------------------------------------------
Column: CredStill_Electives (16 unique values)
[1.  1.5 3.  2.  2.5 0.5 0.  nan 3.5 4. ]
--------------------------------------------------
Column: CredStill_Health/ PersonalFitness (6 unique values)
[0.5  0.   1.    nan 0.88 0.09]
--------------------------------------------------
Column: CredStill_Math (14 unique values)
[1.5 0.  1.  2.  0.5 nan 2.5 3.  3.5 4. ]
--------------------------------------------------
Column: CredStill_Science (16 unique values)
[1.5 0.  1.  0.5 nan 2.  3.  2.5 3.5 4. ]
--------------------------------------------------
Column: CredStill_Social Studies (10 unique values)
[1.   1.5  0.5  0.    nan 2.   2.5  3.   1.67 1.25]
--------------------------------------------------
Column: CredStill_World Language/ FineArts/ CareerTech (11 unique values)
[0.   0.5   nan 1.   2.   1.5  3.   2.5  0.75 2.25]
--------------------------------------------------

In [29]:
# Ensure both have consistent column name
final_student_ids = final_df['student_id'].astype(str).unique()
illuminate['student_id'] = illuminate['student_id'].astype(str)

# Filter illuminate based on student_id in final_df
illuminate_filtered = illuminate[illuminate['student_id'].isin(final_student_ids)].copy()

# Map 'title' column to standardized 'DepartmentDesc'
title_map = {
    'language arts': 'LANGUAGE ARTS',
    'Language Arts': 'LANGUAGE ARTS',
    'math': 'MATH',
    'social sciences': 'SOCIAL SCIENCES',
    'Science': 'SCIENCE'
}
illuminate_filtered['DepartmentDesc'] = illuminate_filtered['title'].map(title_map)
illuminate_filtered.drop(columns=['title'], inplace=True)

In [15]:
# title_map = {
#     'language arts': 'LANGUAGE ARTS',
#     'Language Arts': 'LANGUAGE ARTS',
#     'math': 'MATH',
#     'social sciences': 'SOCIAL SCIENCES',
#     'Science': 'SCIENCE'
# }
# illuminate_filtered['Department'] = illuminate_filtered['Department'].map(title_map)

In [30]:
# Drop columns from illuminate_filtered
# illuminate_filtered.drop(columns=[
#     "CurrentSchoolDetailFCSID",
#     "SchoolId",
#     "stdgrouping",
#     "CurrentSchoolName",
#     "standard_id"
# ], inplace=True)

# Export the cleaned DataFrame to CSV
illuminate_filtered.to_csv("cleaned_illuminate.csv", index=False)

In [17]:
for col in illuminate_filtered.columns:
    unique_vals = illuminate_filtered[col].unique()
    print(f"Column: {col} ({len(unique_vals)} unique values)")
    print(unique_vals[:10])  # Show first 10
    print("-" * 50)

Column: schoolyearnumberspring (1 unique values)
[2025]
--------------------------------------------------
Column: unitnumber (13 unique values)
['4' '2' '1' '6' '5' '5A' '3' '4A' '7' '5B']
--------------------------------------------------
Column: student_id (19158 unique values)
['728618' '391268' '368109' '332765' '314909' '765900' '762208' '410786'
 '574835' '445055']
--------------------------------------------------
Column: AssessmentId (72 unique values)
[379314 370501 355450 341204 395513 338346 391222 341203 383428 393610]
--------------------------------------------------
Column: responsedatevalue (214 unique values)
['2025-02-14 00:00:00' '2024-11-18 00:00:00' '2024-10-01 00:00:00'
 '2024-09-16 00:00:00' '2025-04-03 00:00:00' '2024-12-06 00:00:00'
 '2025-04-02 00:00:00' '2025-03-10 00:00:00' '2024-09-12 00:00:00'
 '2024-09-19 00:00:00']
--------------------------------------------------
Column: DateValue (214 unique values)
['2025-02-14 00:00:00' '2024-11-18 00:00:00' '2024-10-01 00:00:00'
 '2024-09-16 00:00:00' '2025-04-03 00:00:00' '2024-12-06 00:00:00'
 '2025-04-02 00:00:00' '2025-03-10 00:00:00' '2024-09-12 00:00:00'
 '2024-09-19 00:00:00']
--------------------------------------------------
Column: Response_points (207 unique values)
[12.   30.   17.   13.   25.   10.   11.   27.   20.67 14.  ]
--------------------------------------------------
Column: Response_points_possible (15 unique values)
[17. 31. 15. 27. 16. 14. 35. 19. 13. 37.]
--------------------------------------------------
Column: Response_percent_correct (674 unique values)
[ 70.59  96.77 100.    86.67  92.59  58.82  68.75  66.67  85.71  66.68]
--------------------------------------------------
Column: Department (4 unique values)
['LANGUAGE ARTS' 'SOCIAL SCIENCES' 'MATH' 'SCIENCE']
--------------------------------------------------
Column: rn (1 unique values)
[1]
--------------------------------------------------
Column: StandardStateNumber (420 unique values)
['ELAGSE9-10L2a' 'SSUSH8.c' 'ELAGSE9-10RI2' 'ELAGSE11-12W1e' 'SSUSH22.a'
 'ELAGSE9-10RI4' 'G.GSR.5.1' 'ELAGSE9-10RI5' 'SSUSH20.c' 'ELAGSE11-12RI2']
--------------------------------------------------
Column: Standard_Subject (4 unique values)
['English Language Arts' 'Social Studies'
 'Georgia’s K-12 Mathematics Standards' 'Science']
--------------------------------------------------
Column: Standard_points (43 unique values)
[1.   0.   6.   2.   3.   1.5  0.67 5.   1.67 0.5 ]
--------------------------------------------------
Column: Standard_points_possible (11 unique values)
[ 1.  6.  3.  2.  4. 10.  7.  5.  8.  0.]
--------------------------------------------------
Column: Standard_percent_correct (91 unique values)
[100.     0.    66.67  50.    75.    67.    33.33  60.    16.67  14.29]
--------------------------------------------------
Column: condition (3 unique values)
['Extension' 'Reteach' 'Review & Practice']
--------------------------------------------------
Column: pointsvarchar (66 unique values)
['1/1' '0/1' '6/6' '2/3' '1/2' '3/3' '2/2' '2/4' '1/3' '6/10']
--------------------------------------------------
Column: categorytitle (16 unique values)
['Grades: 9-10' 'United States History' 'Grades: 11-12'
 'High School – Geometry: Concepts and Connections' 'Biology'
 'High School – Algebra: Concepts and Connections'
 'High School – Precalculus'
 'High School – Advanced Algebra: Concepts and Connections'
 'Physical Science' 'Grade 7']
--------------------------------------------------
Column: GradeLevelDuringUnitTest (4 unique values)
['09' '11' '10' '12']
--------------------------------------------------
Column: ContinuousAchievementLevel (6 unique values)
['On Level' 'Advanced' 'Not Applicable' nan 'Enhanced' 'Accelerated']
--------------------------------------------------
Column: AssessmentGradeLevel (9 unique values)
['10' 'HS' '11' '9' '7' '8' '3' '4' '6']
--------------------------------------------------
Column: DepartmentDesc (4 unique values)
['LANGUAGE ARTS' 'SOCIAL SCIENCES' 'MATH' 'SCIENCE']
--------------------------------------------------

In [32]:
display(illuminate_filtered[illuminate_filtered['student_id'] == '368109'])

,schoolyearnumberspring,unitnumber,student_id,AssessmentId,responsedatevalue,DateValue,Response_points,Response_points_possible,Response_percent_correct,Department,...,condition,pointsvarchar,categorytitle,stdgrouping,SchoolId,GradeLevelDuringUnitTest,ContinuousAchievementLevel,AssessmentGradeLevel,CurrentSchoolDetailFCSID,DepartmentDesc
16,2025,1,368109,355450,2024-10-01 00:00:00,2024-10-01 00:00:00,17.0,17.0,100.00,language arts,...,Extension,6/6,Grades: 9-10,ELAGSE9-10RI2 Determine a central idea of a te...,83,09,Advanced,10,914,LANGUAGE ARTS
23326,2025,4,368109,379314,2025-02-24 00:00:00,2025-02-24 00:00:00,17.0,17.0,100.00,language arts,...,Extension,6/6,Grades: 9-10,ELAGSE9-10RL2 Determine a theme or central ide...,83,09,Advanced,10,914,LANGUAGE ARTS
59227,2025,1,368109,356733,2024-09-10 00:00:00,2024-09-10 00:00:00,14.0,14.0,100.00,Science,...,Extension,2/2,Biology,SB5.e Construct explanations that predict an o...,83,09,Not Applicable,HS,914,SCIENCE
94232,2025,4,368109,379247,2025-02-27 00:00:00,2025-02-27 00:00:00,15.0,19.0,78.95,Science,...,Reteach,2/3,Biology,SB6.b Analyze and interpret data to explain pa...,83,09,Not Applicable,HS,914,SCIENCE
130417,2025,6,368109,338350,2025-03-17 00:00:00,2025-03-17 00:00:00,8.0,15.0,53.33,math,...,Reteach,2/3,High School – Geometry: Concepts and Connections,G.GSR.7.3 Use special right triangles on the u...,83,09,Enhanced,HS,914,MATH
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4667050,2025,1,368109,355450,2024-10-01 00:00:00,2024-10-01 00:00:00,17.0,17.0,100.00,language arts,...,Extension,2/2,Grades: 9-10,"ELAGSE9-10L4a Use context (e.g., the overall m...",83,09,Advanced,10,914,LANGUAGE ARTS
4706927,2025,3,368109,378813,2025-03-11 00:00:00,2025-03-11 00:00:00,9.0,15.0,60.00,Science,...,Reteach,1/3,Biology,SB3.b Use mathematical models to predict and e...,83,09,Not Applicable,HS,914,SCIENCE
4801497,2025,4,368109,379247,2025-02-27 00:00:00,2025-02-27 00:00:00,15.0,19.0,78.95,Science,...,Reteach,2/3,Biology,SB6.a Construct an explanation of how new unde...,83,09,Not Applicable,HS,914,SCIENCE
4836828,2025,1,368109,356733,2024-09-10 00:00:00,2024-09-10 00:00:00,14.0,14.0,100.00,Science,...,Extension,3/3,Biology,SB5.c Construct an argument to predict the imp...,83,09,Not Applicable,HS,914,SCIENCE
4845508,2025,3,368109,380389,2024-12-13 00:00:00,2024-12-13 00:00:00,17.0,17.0,100.00,language arts,...,Extension,1/1,Grades: 11-12,ELAGSE11-12RI2 Determine two or more central i...,83,09,Advanced,10,914,LANGUAGE ARTS

In [33]:
test = pd.read_csv(
    os.path.join(directory_path, "Data/cleaned_illuminate.csv"),
    low_memory=True
)
display(test[test['student_id'] == 368109])

,student_id,Department,StandardGradeLevel,Response_percent_correct,responsedatevalue,condition,StandardStateNumber
3,368109,LANGUAGE ARTS,9.0,100.00,2024-10-01,Extension,ELAGSE9-10RI2
2013,368109,LANGUAGE ARTS,9.0,100.00,2025-02-24,Extension,ELAGSE9-10RL2
11801,368109,LANGUAGE ARTS,9.0,100.00,2025-02-24,Extension,ELAGSE9-10L2a
12610,368109,LANGUAGE ARTS,9.0,100.00,2024-10-01,Extension,ELAGSE9-10RI3
50551,368109,LANGUAGE ARTS,9.0,100.00,2024-10-01,Extension,ELAGSE9-10RI4
60543,368109,LANGUAGE ARTS,9.0,100.00,2024-12-13,Extension,ELAGSE9-10RI9
72558,368109,LANGUAGE ARTS,9.0,100.00,2024-12-13,Extension,ELAGSE9-10RI8
107051,368109,LANGUAGE ARTS,9.0,94.44,2024-11-13,Extension,ELAGSE9-10L4a
113557,368109,LANGUAGE ARTS,9.0,94.44,2024-11-13,Review & Practice,ELAGSE9-10RL2
127722,368109,LANGUAGE ARTS,9.0,100.00,2025-02-24,Extension,ELAGSE9-10RL3
215924,368109,LANGUAGE ARTS,9.0,100.00,2024-12-13,Extension,ELAGSE9-10RI2
232012,368109,LANGUAGE ARTS,9.0,100.00,2025-02-24,Extension,ELAGSE9-10RL5
240125,368109,LANGUAGE ARTS,9.0,100.00,2024-12-13,Extension,ELAGSE9-10L1a
243628,368109,LANGUAGE ARTS,9.0,100.00,2024-12-13,Extension,ELAGSE9-10RI5
260880,368109,LANGUAGE ARTS,9.0,100.00,2025-02-24,Extension,ELAGSE9-10W5
276344,368109,LANGUAGE ARTS,9.0,100.00,2024-10-01,Extension,ELAGSE9-10L2b
296933,368109,LANGUAGE ARTS,9.0,94.44,2024-11-13,Extension,ELAGSE9-10W3d
298313,368109,LANGUAGE ARTS,9.0,100.00,2025-02-24,Extension,ELAGSE9-10RL1
320409,368109,LANGUAGE ARTS,9.0,100.00,2024-12-13,Extension,ELAGSE9-10RI6
330070,368109,LANGUAGE ARTS,9.0,100.00,2024-10-01,Extension,ELAGSE9-10W2a
333950,368109,LANGUAGE ARTS,9.0,94.44,2024-11-13,Extension,ELAGSE9-10RL4
356511,368109,LANGUAGE ARTS,9.0,94.44,2024-11-13,Extension,ELAGSE9-10RL3
358343,368109,LANGUAGE ARTS,9.0,100.00,2024-10-01,Extension,ELAGSE9-10RI8
385374,368109,LANGUAGE ARTS,9.0,94.44,2024-11-13,Extension,ELAGSE9-10L5a
394447,368109,LANGUAGE ARTS,9.0,94.44,2024-11-13,Extension,ELAGSE9-10RL5
403760,368109,LANGUAGE ARTS,9.0,100.00,2024-12-13,Extension,ELAGSE9-10RI4
410109,368109,LANGUAGE ARTS,9.0,100.00,2024-10-01,Extension,ELAGSE9-10RI9
416908,368109,LANGUAGE ARTS,9.0,100.00,2024-10-01,Extension,ELAGSE9-10L4a
432789,368109,LANGUAGE ARTS,11.0,100.00,2024-12-13,Extension,ELAGSE11-12RI2